apiVersion: v1
kind: Service
metadata:
  name: bella-frontend
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: bella-frontend